// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations.Postgres
{
    [DbContext(typeof(PostgresAppDbContext))]
    partial class PostgresAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Auth.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Auth.VerificationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptsCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempts_count");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean")
                        .HasColumnName("used");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Purpose", "CreatedAt");

                    b.ToTable("verification_codes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Card.CardInstallment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("CardInvoiceId")
                        .HasColumnType("integer")
                        .HasColumnName("card_invoice_id");

                    b.Property<int>("CardPurchaseId")
                        .HasColumnType("integer")
                        .HasColumnName("card_purchase_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("InstallmentNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("installment_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CardInvoiceId");

                    b.HasIndex("CardPurchaseId");

                    b.HasIndex("UserId");

                    b.ToTable("card_installment", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Card.CardInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ClosingDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("closing_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreditCardId")
                        .HasColumnType("integer")
                        .HasColumnName("credit_card_id");

                    b.Property<DateTime>("DueDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("due_date");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<short>("ReferenceMonth")
                        .HasColumnType("smallint")
                        .HasColumnName("reference_month");

                    b.Property<short>("ReferenceYear")
                        .HasColumnType("smallint")
                        .HasColumnName("reference_year");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreditCardId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId", "CreditCardId", "ReferenceYear", "ReferenceMonth")
                        .IsUnique();

                    b.ToTable("card_invoice", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Card.CardPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int?>("CategoryItemId")
                        .HasColumnType("integer")
                        .HasColumnName("category_item_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreditCardId")
                        .HasColumnType("integer")
                        .HasColumnName("credit_card_id");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("description");

                    b.Property<short>("InstallmentsCount")
                        .HasColumnType("smallint")
                        .HasColumnName("installments_count");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("origin");

                    b.Property<DateTime>("PurchaseDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("purchase_date");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CategoryItemId");

                    b.HasIndex("CreditCardId");

                    b.HasIndex("UserId", "CreditCardId");

                    b.ToTable("card_purchase", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Card.CreditCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<int>("BankId")
                        .HasColumnType("integer")
                        .HasColumnName("bank_id");

                    b.Property<short>("ClosingDay")
                        .HasColumnType("smallint")
                        .HasColumnName("closing_day");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("credit_limit");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("description");

                    b.Property<short>("DueDay")
                        .HasColumnType("smallint")
                        .HasColumnName("due_day");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("UserId", "Description")
                        .IsUnique();

                    b.ToTable("credit_card", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Configuration.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("CodTypeTransaction")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("cod_type_transaction");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("description");

                    b.Property<bool>("IsCardInvoiceCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_card_invoice_category");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CodTypeTransaction");

                    b.HasIndex("UserId", "Description")
                        .IsUnique();

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Configuration.CategoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("category_item", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Configuration.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("description");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Description")
                        .IsUnique();

                    b.ToTable("payment_method", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DataRetention.DataRetentionPurgeRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastRunAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("last_run_at");

                    b.HasKey("Id");

                    b.ToTable("data_retention_purge_runs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Gamification.ConsistencyCounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BestStreak")
                        .HasColumnType("integer")
                        .HasColumnName("best_streak");

                    b.Property<string>("CounterKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("counter_key");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer")
                        .HasColumnName("current_streak");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CounterKey")
                        .IsUnique();

                    b.ToTable("consistency_counters", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Gamification.GamificationEvaluationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BadgesUnlocked")
                        .HasColumnType("integer")
                        .HasColumnName("badges_unlocked");

                    b.Property<int>("EventsTriggered")
                        .HasColumnType("integer")
                        .HasColumnName("events_triggered");

                    b.Property<DateTime>("RanAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("ran_at");

                    b.Property<int>("UsersProcessed")
                        .HasColumnType("integer")
                        .HasColumnName("users_processed");

                    b.HasKey("Id");

                    b.ToTable("gamification_evaluation_runs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Gamification.MissionStateSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsConditionActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_condition_active");

                    b.Property<DateTime>("LastEvaluatedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("last_evaluated_at");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("integer")
                        .HasColumnName("related_entity_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Type", "RelatedEntityId")
                        .IsUnique();

                    b.ToTable("mission_state_snapshots", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Gamification.PointLedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OccurredAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("PointsDelta")
                        .HasColumnType("integer")
                        .HasColumnName("points_delta");

                    b.Property<int>("Significance")
                        .HasColumnType("integer")
                        .HasColumnName("significance");

                    b.Property<int>("TierAtEvent")
                        .HasColumnType("integer")
                        .HasColumnName("tier_at_event");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "OccurredAt");

                    b.ToTable("point_ledger_entries", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Gamification.UserBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    b.Property<DateTime>("UnlockedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("unlocked_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Code")
                        .IsUnique();

                    b.ToTable("user_badges", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Gamification.UserRankProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("tier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_rank_profiles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Goals.CategoryBudgetGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<decimal>("MonthlyLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monthly_limit");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "CategoryId");

                    b.ToTable("category_budget_goals", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Goals.FinancialGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CurrentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("current_amount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastContributionAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("last_contribution_at");

                    b.Property<int?>("PreviousAttemptGoalId")
                        .HasColumnType("integer")
                        .HasColumnName("previous_attempt_goal_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TargetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("target_amount");

                    b.Property<DateTime>("TargetDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("target_date");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("financial_goals", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Notifications.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Criticality")
                        .HasColumnType("integer")
                        .HasColumnName("criticality");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_resolved");

                    b.Property<string>("MessageKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("message_key");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("integer")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("related_entity_type");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsArchived", "ArchivedAt");

                    b.HasIndex("UserId", "IsArchived", "IsRead");

                    b.HasIndex("UserId", "IsResolved", "Criticality");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Notifications.NotificationEvaluationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastRunAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("last_run_at");

                    b.HasKey("Id");

                    b.ToTable("notification_evaluation_runs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Notifications.NotificationPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EmailOnCritical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("email_on_critical");

                    b.Property<bool>("EmailOnImportant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("email_on_important");

                    b.Property<bool>("EmailOnInformative")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_on_informative");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("notification_preferences", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Planning.PlannedCommitment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("description");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("direction");

                    b.Property<DateTime?>("EndDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Periodicity")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("periodicity");

                    b.Property<DateTime>("StartDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "Active");

                    b.ToTable("planned_commitment", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Transactions.StatusTransaction", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("description");

                    b.HasKey("Code");

                    b.ToTable("status_transaction", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "O",
                            Description = "Open"
                        },
                        new
                        {
                            Code = "P",
                            Description = "Paid"
                        },
                        new
                        {
                            Code = "C",
                            Description = "Canceled"
                        },
                        new
                        {
                            Code = "E",
                            Description = "Expired"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Transactions.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int?>("CategoryItemId")
                        .HasColumnType("integer")
                        .HasColumnName("category_item_id");

                    b.Property<string>("CodTypeTransaction")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("cod_type_transaction");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<int>("IdPaymentMethod")
                        .HasColumnType("integer")
                        .HasColumnName("id_payment_method");

                    b.Property<short?>("Installments")
                        .HasColumnType("smallint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("status");

                    b.Property<DateTime>("TransactionDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<int?>("TransactionGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_group_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CategoryItemId");

                    b.HasIndex("CodTypeTransaction");

                    b.HasIndex("IdPaymentMethod");

                    b.HasIndex("Status");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("TransactionGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("transaction", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Transactions.TransactionGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<short?>("Installments")
                        .HasColumnType("smallint")
                        .HasColumnName("installments");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("UserId");

                    b.ToTable("transaction_group", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.banks.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("image_url");

                    b.Property<string>("InstitutionUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("institution_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("primary_color");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("bank", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://cdn.pluggy.ai/assets/connector-icons/804.png",
                            Name = "99Pay",
                            PrimaryColor = "#ef294b",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://www.agorainvest.com.br/images/OpenFinance/agora.svg",
                            Name = "Ágora Investimentos",
                            PrimaryColor = "#296fa7",
                            Type = "INVESTMENT"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://cdn.pluggy.ai/assets/connector-icons/883.svg",
                            Name = "ASA",
                            PrimaryColor = "#2b56c0",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://cdn.pluggy.ai/assets/connector-icons/230.svg",
                            Name = "Avenue",
                            PrimaryColor = "#000000",
                            Type = "INVESTMENT"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://www.bancobmg.com.br/data/files/8C/A2/7F/0A/FBA318104A94D208970BE9C2/bmg_open_finance.svg",
                            Name = "Banco Bmg",
                            PrimaryColor = "#fa6300",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://cdn.pluggy.ai/assets/connector-icons/682.svg",
                            Name = "Banco BRB",
                            PrimaryColor = "#003D7C",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://static.digio.com.br/media/logo_81e95ae2ab.svg",
                            Name = "Banco Digio",
                            PrimaryColor = "#ff6776",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://www.bb.com.br/docs/pub/inst/img/LogoBB.svg",
                            Name = "Banco do Brasil",
                            PrimaryColor = "#1194F6",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://cdn.pluggy.ai/assets/connector-icons/671.svg",
                            Name = "Banco do Nordeste",
                            PrimaryColor = "#ef294b",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://cdn.pluggy.ai/assets/connector-icons/742.svg",
                            Name = "Banco Mercantil",
                            PrimaryColor = "#ef294b",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://cdn.pluggy.ai/assets/connector-icons/657.svg",
                            Name = "Banco PAN",
                            PrimaryColor = "#02afff",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://www.sofisa.com.br/openbanking/logo_sofisa.svg",
                            Name = "Banco Sofisa",
                            PrimaryColor = "#004e46",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 13,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://banrisul.com.br/bob/data/Simbolo-Banrisul.svg",
                            Name = "Banrisul",
                            PrimaryColor = "#0B45E4",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 14,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://banco.bradesco/open-finance/logo/icones_vetorial-pf.svg",
                            Name = "Bradesco",
                            PrimaryColor = "#e5173f",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 15,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://cdn.pluggy.ai/assets/connector-icons/203.svg",
                            Name = "Bradesco Cartões",
                            PrimaryColor = "#e5173f",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 16,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://banking-public-prd.s3.sa-east-1.amazonaws.com/open-finance/logo/btgbanking/btgbanking.svg",
                            Name = "BTG Pactual",
                            PrimaryColor = "#66768F",
                            Type = "INVESTMENT"
                        },
                        new
                        {
                            Id = 17,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://www.bv.com.br/site/resources/open-finance/logo-bv.svg",
                            Name = "BV",
                            PrimaryColor = "#223AD2",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 18,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://cdn.pluggy.ai/assets/connector-icons/726.svg",
                            Name = "C6 Bank",
                            PrimaryColor = "#FFE45C",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 19,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://consentimento.openbanking.caixa.gov.br/assets/images/logomarca_caixa.svg",
                            Name = "Caixa Econômica Federal",
                            PrimaryColor = "#296fa7",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 20,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://cdn.pluggy.ai/assets/connector-icons/250.svg",
                            Name = "Cora",
                            PrimaryColor = "#f51b81",
                            Type = "BUSINESS_BANK"
                        },
                        new
                        {
                            Id = 21,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://cdn.pluggy.ai/assets/connector-icons/250.svg",
                            Name = "Conta Simples",
                            PrimaryColor = "#2DCC68",
                            Type = "BUSINESS_BANK"
                        },
                        new
                        {
                            Id = 22,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://cdn.pluggy.ai/assets/connector-icons/750.svg",
                            Name = "Crefisa",
                            PrimaryColor = "#23b9e2",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 23,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://cdn.pluggy.ai/assets/connector-icons/810.svg",
                            Name = "Dock",
                            PrimaryColor = "#ef294b",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 24,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://cdn.pluggy.ai/assets/connector-icons/239.svg",
                            Name = "Efí Bank",
                            PrimaryColor = "#fb6910",
                            Type = "BUSINESS_BANK"
                        },
                        new
                        {
                            Id = 25,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://cdn.pluggy.ai/assets/connector-icons/271.svg",
                            Name = "EQI Investimentos",
                            PrimaryColor = "#DB671F",
                            Type = "INVESTMENT"
                        },
                        new
                        {
                            Id = 26,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://cdn.pluggy.ai/assets/connector-icons/215.svg",
                            Name = "Inter",
                            PrimaryColor = "#fb6910",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 27,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://www.itau.com.br/assets/dam/publisher/07_itau_empresas/13_open_banking/logos_regulatorio_bacen/opb_log_reg_bac_itau_img_01.svg",
                            Name = "Itaú",
                            PrimaryColor = "#EC7000",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 28,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://http2.mlstatic.com/frontend-assets/opb-logos/logo.svg",
                            Name = "Mercado Pago",
                            PrimaryColor = "#009ee3",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 29,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://nuapp.nubank.com.br/open-banking/logo.svg",
                            Name = "Nubank",
                            PrimaryColor = "#8a0fbe",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 30,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://cdn.pluggy.ai/assets/connector-icons/692.svg",
                            Name = "PagBank",
                            PrimaryColor = "#ef294b",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 31,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://picpay.s3.sa-east-1.amazonaws.com/openbanking/picpay-logo-icon-pf.svg",
                            Name = "PicPay",
                            PrimaryColor = "#238662",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 32,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://cdn.pluggy.ai/assets/connector-icons/205.svg",
                            Name = "Rico Investimentos",
                            PrimaryColor = "#ff5200",
                            Type = "INVESTMENT"
                        },
                        new
                        {
                            Id = 33,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://storage.googleapis.com/inic-data/safra-pf.svg",
                            Name = "Safra",
                            PrimaryColor = "#00003C",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 34,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://cms.santander.com.br/sites/WPS/imagem/img-santander-chama/21-08-06_200409_P_santander_chama.svg",
                            Name = "Santander",
                            PrimaryColor = "#cc0000",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 35,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://sicoob-openbanking.s3.sa-east-1.amazonaws.com/logo-sicoob.svg",
                            Name = "Sicoob",
                            PrimaryColor = "#00AE9D",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 36,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://www.sicredi.com.br/openbanking/app/assets/images/shared/logo/logo_sicredi_512.svg",
                            Name = "Sicredi",
                            PrimaryColor = "#3FA110",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 37,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://cdn.pluggy.ai/assets/connector-icons/787.svg",
                            Name = "Stone",
                            PrimaryColor = "#00A868",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 38,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://cdn.pluggy.ai/assets/connector-icons/796.svg",
                            Name = "Toro Investimentos",
                            PrimaryColor = "#ef294b",
                            Type = "INVESTMENT"
                        },
                        new
                        {
                            Id = 39,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://www.unicred.com.br/logo.svg",
                            Name = "Unicred",
                            PrimaryColor = "#1e5c49",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 40,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://cdn.pluggy.ai/assets/connector-icons/291.svg",
                            Name = "Wise",
                            PrimaryColor = "#9fe870",
                            Type = "PERSONAL_BANK"
                        },
                        new
                        {
                            Id = 41,
                            Active = true,
                            ImageUrl = "",
                            InstitutionUrl = "https://cdn.pluggy.ai/assets/connector-icons/202.svg",
                            Name = "XP Investimentos",
                            PrimaryColor = "#111111",
                            Type = "INVESTMENT"
                        });
                });

            modelBuilder.Entity("Domain.Entities.banks.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<int>("BankConnectionId")
                        .HasColumnType("integer")
                        .HasColumnName("bank_connection_id");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("current_balance");

                    b.Property<string>("ExternalAccountId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_account_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("BankConnectionId");

                    b.ToTable("bank_account", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.banks.BankConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalConnectionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_connection_id");

                    b.Property<string>("InstitutionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("institution_code");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("institution_name");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("UserId");

                    b.ToTable("bank_connection", (string)null);
                });

            modelBuilder.Entity("KronPay.Domain.Entities.Configuration.TypeTransaction", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("description");

                    b.HasKey("Code");

                    b.ToTable("type_transaction", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "I",
                            Description = "Income"
                        },
                        new
                        {
                            Code = "E",
                            Description = "Expense"
                        },
                        new
                        {
                            Code = "V",
                            Description = "Investment"
                        },
                        new
                        {
                            Code = "R",
                            Description = "Redemption"
                        });
                });

            modelBuilder.Entity("KronPay.Domain.Entities.Users.TypeUser", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("description");

                    b.HasKey("Code");

                    b.ToTable("type_user", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "A",
                            Description = "Admin"
                        },
                        new
                        {
                            Code = "P",
                            Description = "Premium"
                        },
                        new
                        {
                            Code = "B",
                            Description = "Basic"
                        },
                        new
                        {
                            Code = "V",
                            Description = "VIP"
                        },
                        new
                        {
                            Code = "C",
                            Description = "Corporate"
                        });
                });

            modelBuilder.Entity("KronPay.Domain.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<DateTime?>("LastAccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_Access_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("cod_user_type");

                    b.HasKey("Id");

                    b.HasIndex("UserType");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("KronPay.Domain.Entities.Users.UserProfilePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("content_type");

                    b.Property<byte[]>("Photo")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("photo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profile_photos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Auth.RefreshToken", b =>
                {
                    b.HasOne("KronPay.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Auth.VerificationCode", b =>
                {
                    b.HasOne("KronPay.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Card.CardInstallment", b =>
                {
                    b.HasOne("Domain.Entities.Card.CardInvoice", "CardInvoice")
                        .WithMany()
                        .HasForeignKey("CardInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Card.CardPurchase", "CardPurchase")
                        .WithMany()
                        .HasForeignKey("CardPurchaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KronPay.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CardInvoice");

                    b.Navigation("CardPurchase");
                });

            modelBuilder.Entity("Domain.Entities.Card.CardInvoice", b =>
                {
                    b.HasOne("Domain.Entities.Card.CreditCard", null)
                        .WithMany()
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Transactions.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KronPay.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Domain.Entities.Card.CardPurchase", b =>
                {
                    b.HasOne("Domain.Entities.Configuration.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Configuration.CategoryItem", null)
                        .WithMany()
                        .HasForeignKey("CategoryItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Card.CreditCard", null)
                        .WithMany()
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KronPay.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Card.CreditCard", b =>
                {
                    b.HasOne("Domain.Entities.banks.Bank", null)
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KronPay.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Configuration.Category", b =>
                {
                    b.HasOne("KronPay.Domain.Entities.Configuration.TypeTransaction", null)
                        .WithMany()
                        .HasForeignKey("CodTypeTransaction")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KronPay.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Configuration.CategoryItem", b =>
                {
                    b.HasOne("Domain.Entities.Configuration.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Configuration.PaymentMethod", b =>
                {
                    b.HasOne("KronPay.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Gamification.ConsistencyCounter", b =>
                {
                    b.HasOne("KronPay.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Gamification.MissionStateSnapshot", b =>
                {
                    b.HasOne("KronPay.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Gamification.PointLedgerEntry", b =>
                {
                    b.HasOne("KronPay.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Gamification.UserBadge", b =>
                {
                    b.HasOne("KronPay.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Gamification.UserRankProfile", b =>
                {
                    b.HasOne("KronPay.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Goals.CategoryBudgetGoal", b =>
                {
                    b.HasOne("Domain.Entities.Configuration.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Notifications.Notification", b =>
                {
                    b.HasOne("KronPay.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Notifications.NotificationPreference", b =>
                {
                    b.HasOne("KronPay.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Planning.PlannedCommitment", b =>
                {
                    b.HasOne("Domain.Entities.Configuration.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KronPay.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Transactions.Transaction", b =>
                {
                    b.HasOne("Domain.Entities.Configuration.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Configuration.CategoryItem", null)
                        .WithMany()
                        .HasForeignKey("CategoryItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KronPay.Domain.Entities.Configuration.TypeTransaction", null)
                        .WithMany()
                        .HasForeignKey("CodTypeTransaction")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Configuration.PaymentMethod", null)
                        .WithMany()
                        .HasForeignKey("IdPaymentMethod")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Transactions.StatusTransaction", null)
                        .WithMany()
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Transactions.TransactionGroup", "TransactionGroup")
                        .WithMany()
                        .HasForeignKey("TransactionGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KronPay.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TransactionGroup");
                });

            modelBuilder.Entity("Domain.Entities.banks.BankAccount", b =>
                {
                    b.HasOne("Domain.Entities.banks.BankConnection", "BankConnection")
                        .WithMany("BankAccounts")
                        .HasForeignKey("BankConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankConnection");
                });

            modelBuilder.Entity("KronPay.Domain.Entities.Users.User", b =>
                {
                    b.HasOne("KronPay.Domain.Entities.Users.TypeUser", null)
                        .WithMany()
                        .HasForeignKey("UserType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.User.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("character varying(14)")
                                .HasColumnName("cpf");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Domain.ValueObjects.User.Phone", "Phone", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("phone");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Email", "Email", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("name");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Name", "Username", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("username");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Cpf")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();

                    b.Navigation("Username")
                        .IsRequired();
                });

            modelBuilder.Entity("KronPay.Domain.Entities.Users.UserProfilePhoto", b =>
                {
                    b.HasOne("KronPay.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.banks.BankConnection", b =>
                {
                    b.Navigation("BankAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
