namespace Domain.Enums.Gamification;

public enum BadgeCode
{
    FirstSteps,
    BreakingTheIce,
    Explorer,
    FirstGoal,
    AllConnected,
    FutureVision,
    FirstCategory,
    FirstMission,
    MultipleCards,
    FirstPositiveMonth,
    FirstInvoiceOnTime,
    OrganizedMonth,
    FirstGoalAchieved,
    FirstInvestment,
    NoPendingAlerts,
    FirstBudgetMet,

    IronDiscipline,
    FlawlessQuarter,
    SolidReserve,
    ConsistentInvestor,
    NoLatePayments,
    QuarterInTheBlack,
    DiligentPlanner,
    DoubleGoalAchiever,
    NoRelapses,
    QuickResponder,
    TrendReverser,
    WideBudgetCoverage,
    RecoveredGoal,
    SixMonthsFocused,

    PerfectYear,
    RobustReserve,
    DedicatedInvestor,
    PositiveFiscalYear,
    IronDisciplineIII,
    GoldenStreak,
    AmbitiousGoalAchieved,
    NoLatePaymentsYear,
    PlanningMaster,
    Resilient,
    PlanningLegend,
    CompleteCollection
}
