//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Acumulado.
        /// </summary>
        public static string Accumulated {
            get {
                return ResourceManager.GetString("Accumulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Acões.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicionar.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a adicionar categoria.
        /// </summary>
        public static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicionar forma de pagamento.
        /// </summary>
        public static string AddPaymentMethod {
            get {
                return ResourceManager.GetString("AddPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicionar sub categoria.
        /// </summary>
        public static string AddSubcategory {
            get {
                return ResourceManager.GetString("AddSubcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Todos.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Somente arquivos CSV ou OFX são permitidos..
        /// </summary>
        public static string AllowedFiles {
            get {
                return ResourceManager.GetString("AllowedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resumo Anual.
        /// </summary>
        public static string AnnualSummary {
            get {
                return ResourceManager.GetString("AnnualSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ABR.
        /// </summary>
        public static string APR {
            get {
                return ResourceManager.GetString("APR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você tem certeza que deseja excluir esse dado?.
        /// </summary>
        public static string AreYouSureRemoveData {
            get {
                return ResourceManager.GetString("AreYouSureRemoveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vai ser removido todos as parcelas referente a essa transação, você tem certeza que deseja excluir as parcelas?.
        /// </summary>
        public static string AreYouSureRemoveDataGroup {
            get {
                return ResourceManager.GetString("AreYouSureRemoveDataGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atenção.
        /// </summary>
        public static string Atention {
            get {
                return ResourceManager.GetString("Atention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Anexar.
        /// </summary>
        public static string Attach {
            get {
                return ResourceManager.GetString("Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AGO.
        /// </summary>
        public static string AUG {
            get {
                return ResourceManager.GetString("AUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Melhor mês.
        /// </summary>
        public static string BestMonth {
            get {
                return ResourceManager.GetString("BestMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categorias.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria não encontrado.
        /// </summary>
        public static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você alterou uma transação parcelada, deseja modificar esse valor para todas as outras parcelas &lt;b&gt;pendentes&lt;/b&gt;?.
        /// </summary>
        public static string ChangeOtherInstallments {
            get {
                return ResourceManager.GetString("ChangeOtherInstallments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cartôes de crédito.
        /// </summary>
        public static string CreditCard {
            get {
                return ResourceManager.GetString("CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gráficos.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data da transação .
        /// </summary>
        public static string DateTransaction {
            get {
                return ResourceManager.GetString("DateTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data em que você efetuou o pagamento ou irá efetuar o pagamento.
        /// </summary>
        public static string DateTransactionInfo {
            get {
                return ResourceManager.GetString("DateTransactionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DEZ.
        /// </summary>
        public static string DEC {
            get {
                return ResourceManager.GetString("DEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Remover.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deleteta todas as parcelas futuras dessa parcela.
        /// </summary>
        public static string DeleteAllInstallments {
            get {
                return ResourceManager.GetString("DeleteAllInstallments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deletar categoria.
        /// </summary>
        public static string DeleteCategory {
            get {
                return ResourceManager.GetString("DeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição já existe.
        /// </summary>
        public static string DescriptionAlreadyExists {
            get {
                return ResourceManager.GetString("DescriptionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não tem uma conta?.
        /// </summary>
        public static string DoNotHaveAccount {
            get {
                return ResourceManager.GetString("DoNotHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a você deseja usar Inteligencia artificial para decidir qual o tipo e categoria da sua transação?.
        /// </summary>
        public static string DoYouWantToUseAi {
            get {
                return ResourceManager.GetString("DoYouWantToUseAi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você deseja apenas vizualizar o anexo para em seguida salvar?.
        /// </summary>
        public static string DoYouWantToView {
            get {
                return ResourceManager.GetString("DoYouWantToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Entrar.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Evolução do investimento do ano.
        /// </summary>
        public static string EvolutionInvestment {
            get {
                return ResourceManager.GetString("EvolutionInvestment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Existe registro vinculado a esse, logo não pode ser desativado.
        /// </summary>
        public static string ExistsAnotherRegister {
            get {
                return ResourceManager.GetString("ExistsAnotherRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Despesa.
        /// </summary>
        public static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Expirado.
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login expirado.
        /// </summary>
        public static string ExpiredToken {
            get {
                return ResourceManager.GetString("ExpiredToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FEV.
        /// </summary>
        public static string FEB {
            get {
                return ResourceManager.GetString("FEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esqueceu sua Senha?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Olá.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Maior despesa.
        /// </summary>
        public static string HigherExpense {
            get {
                return ResourceManager.GetString("HigherExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Maior receita.
        /// </summary>
        public static string HigherIncome {
            get {
                return ResourceManager.GetString("HigherIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Receita.
        /// </summary>
        public static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Receitas x Despesas por mês.
        /// </summary>
        public static string IncomeVsExpensePerMonth {
            get {
                return ResourceManager.GetString("IncomeVsExpensePerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Recorrência mensal contínua.
        /// </summary>
        public static string InfiniteRecurrence {
            get {
                return ResourceManager.GetString("InfiniteRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parcelas.
        /// </summary>
        public static string Installments {
            get {
                return ResourceManager.GetString("Installments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cpf inválido.
        /// </summary>
        public static string InvalidCpf {
            get {
                return ResourceManager.GetString("InvalidCpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Credencial errada.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição Inválida.
        /// </summary>
        public static string InvalidDescription {
            get {
                return ResourceManager.GetString("InvalidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email inválido.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha inválida..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone inválido..
        /// </summary>
        public static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário Inválido.
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ano Inválido.
        /// </summary>
        public static string InvalidYear {
            get {
                return ResourceManager.GetString("InvalidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Investimento.
        /// </summary>
        public static string Investment {
            get {
                return ResourceManager.GetString("Investment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Investimentos.
        /// </summary>
        public static string Investments {
            get {
                return ResourceManager.GetString("Investments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum registro encontrado. Cadastre um novo para poder consulta-lo..
        /// </summary>
        public static string ItemItemNotFound {
            get {
                return ResourceManager.GetString("ItemItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a JAN.
        /// </summary>
        public static string JAN {
            get {
                return ResourceManager.GetString("JAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a JUL.
        /// </summary>
        public static string JUL {
            get {
                return ResourceManager.GetString("JUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a JUN.
        /// </summary>
        public static string JUN {
            get {
                return ResourceManager.GetString("JUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter no mínimo 8 caracteres..
        /// </summary>
        public static string LengthPassword8 {
            get {
                return ResourceManager.GetString("LengthPassword8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter letra minúscula..
        /// </summary>
        public static string LowercaseLetterPassword {
            get {
                return ResourceManager.GetString("LowercaseLetterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Faça login para acessar sua conta.
        /// </summary>
        public static string MakeLoginForAccessYourAccount {
            get {
                return ResourceManager.GetString("MakeLoginForAccessYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MAR.
        /// </summary>
        public static string MAR {
            get {
                return ResourceManager.GetString("MAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MAI.
        /// </summary>
        public static string MAY {
            get {
                return ResourceManager.GetString("MAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mês.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resumo Mensal.
        /// </summary>
        public static string MonthlySummary {
            get {
                return ResourceManager.GetString("MonthlySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Movimentação por dia.
        /// </summary>
        public static string MovementPerDay {
            get {
                return ResourceManager.GetString("MovementPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Meses negativos.
        /// </summary>
        public static string NegativeMonths {
            get {
                return ResourceManager.GetString("NegativeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não Pagas.
        /// </summary>
        public static string NotPaids {
            get {
                return ResourceManager.GetString("NotPaids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não Recebido.
        /// </summary>
        public static string NotReceived {
            get {
                return ResourceManager.GetString("NotReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha não pode conter números em sequência..
        /// </summary>
        public static string NotSequencialNumberPassword {
            get {
                return ResourceManager.GetString("NotSequencialNumberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NOV.
        /// </summary>
        public static string NOV {
            get {
                return ResourceManager.GetString("NOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Objetivos.
        /// </summary>
        public static string Objectives {
            get {
                return ResourceManager.GetString("Objectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OUT.
        /// </summary>
        public static string OCT {
            get {
                return ResourceManager.GetString("OCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pendente.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operação falhou.
        /// </summary>
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sucesso na operação.
        /// </summary>
        public static string OperationSuccess {
            get {
                return ResourceManager.GetString("OperationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ou arraste o arquivo aqui.
        /// </summary>
        public static string OrDragFile {
            get {
                return ResourceManager.GetString("OrDragFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pago.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pagas.
        /// </summary>
        public static string Paids {
            get {
                return ResourceManager.GetString("Paids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter no mínimo 8 caracteres, letra maiúscula, letra minúscula, caractere especial e não pode conter números sequenciais..
        /// </summary>
        public static string PasswordRules {
            get {
                return ResourceManager.GetString("PasswordRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Metodo de pagamento não enontrado.
        /// </summary>
        public static string PaymentMethodNotFound {
            get {
                return ResourceManager.GetString("PaymentMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Forma de pagamento.
        /// </summary>
        public static string PaymentMethods {
            get {
                return ResourceManager.GetString("PaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Meses positivos.
        /// </summary>
        public static string PositiveMonths {
            get {
                return ResourceManager.GetString("PositiveMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Recebido.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conta recorrente (sem parcelas).
        /// </summary>
        public static string RecurringExpense {
            get {
                return ResourceManager.GetString("RecurringExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Use esta opção para despesas que se repetem todos os meses, como assinaturas, e não possuem número fixo de parcelas..
        /// </summary>
        public static string RecurringExpenseDesc {
            get {
                return ResourceManager.GetString("RecurringExpenseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastra-se.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lembre-me.
        /// </summary>
        public static string RemindMe {
            get {
                return ResourceManager.GetString("RemindMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Remover selecionados.
        /// </summary>
        public static string RemoveSelected {
            get {
                return ResourceManager.GetString("RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Relatórios.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resultado.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Existem transações com campos obrigatórios não preenchidos..
        /// </summary>
        public static string SaveAttachInvalid {
            get {
                return ResourceManager.GetString("SaveAttachInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pesquisar.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione ao menos um item para ser removido.
        /// </summary>
        public static string SelectAtLeastOneItemToBeRemoved {
            get {
                return ResourceManager.GetString("SelectAtLeastOneItemToBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SET.
        /// </summary>
        public static string SEP {
            get {
                return ResourceManager.GetString("SEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurações.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter caractere especial..
        /// </summary>
        public static string SpecialCharacter {
            get {
                return ResourceManager.GetString("SpecialCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sub categorias.
        /// </summary>
        public static string Subcategories {
            get {
                return ResourceManager.GetString("Subcategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Transação.
        /// </summary>
        public static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Transação não encontrada para esse período.
        /// </summary>
        public static string TransactionNotFound {
            get {
                return ResourceManager.GetString("TransactionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Transações.
        /// </summary>
        public static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ERRO INESPERADO.
        /// </summary>
        public static string UNEXPECTED_ERROR {
            get {
                return ResourceManager.GetString("UNEXPECTED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter letra maiúscula..
        /// </summary>
        public static string UppercaseLetterPassword {
            get {
                return ResourceManager.GetString("UppercaseLetterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário já existe.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do usuário.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário ou senha está incorreto.
        /// </summary>
        public static string UsernameOrPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("UsernameOrPasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bem vindo de volta.
        /// </summary>
        public static string WelcomeBack {
            get {
                return ResourceManager.GetString("WelcomeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pior mês.
        /// </summary>
        public static string WorstMonth {
            get {
                return ResourceManager.GetString("WorstMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sim.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
